### ISSUE TITLE
Error on deploy to Amazon EKS

### ISSUE THREAD

**Issue by momolog** [getkuby/kuby-core#39] opened 2020-10-26 17:41 UTC
I am trying to deploy to AWS EKS using https://github.com/getkuby/kuby-eks

When executing 
```
RAILS_MASTER_KEY=<my master key> bundle exec kuby -e production deploy
```
I am getting
```
error: 404 Not Found: Not Found
```
This is not a particularly helpful error. How can I proceed from here?

**Comment by camertron** [comment] 2020-10-26 17:53
Hey @momolog, that error usually occurs when Kuby is having trouble communicating with your Docker registry. Some things to check:

1. Have you built and pushed your Docker image? `bundle exec kuby -e production build` and `bundle exec kuby -e production push`.
1. What Docker registry are you using? I just published a fix to the docker-remote gem that fixes an issue with basic auth. You might be affected if you're using Github's package repo. Try running `bundle update --source docker-remote`.

You're right, that's not a great error message. I'll see what I can do to improve it.

**Comment by momolog** [comment] 2020-10-26 18:07
Hey @camertron ,

thanks for your immediate answer.
I am using Amazons Elastic Container Registry (ECR), the build and push seem  to have worked.

After running `bundle update --source docker-remote` I am getting a much more helpful error message: 
```
error: User: arn:aws:iam::186793713737:user/EKS-Cluster-Chef is not authorized to perform: eks:DescribeCluster on resource: arn:aws:eks:eu-central-1:186793713737:cluster/momolog-number1
```
That is something a can look into.

Thanks!

**Comment by momolog** [comment] 2020-10-26 18:26
I am now getting a pretty strange output:
```
error: You must be logged in to the server (Unauthorized)
Refreshing kubeconfig...
Successfully refreshed kubeconfig!
error: You must be logged in to the server (Unauthorized)
Refreshing kubeconfig...
Successfully refreshed kubeconfig!
error: You must be logged in to the server (Unauthorized)
Validating global resource, namespace 'haefner-production'
error: You must be logged in to the server (Unauthorized)
Refreshing kubeconfig...
Successfully refreshed kubeconfig!
error: You must be logged in to the server (the server has asked for the client to provide credentials)
Could not apply namespace 'haefner-production': kubectl exited with status code 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: haefner-production

error: You must be logged in to the server (Unauthorized)
Refreshing kubeconfig...
Successfully refreshed kubeconfig!
[INFO][2020-10-26 19:25:05 +0100]
[INFO][2020-10-26 19:25:05 +0100]	------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2020-10-26 19:25:11 +0100]
[INFO][2020-10-26 19:25:11 +0100]	------------------------------------------Result: FAILURE-------------------------------------------
[FATAL][2020-10-26 19:25:11 +0100]	Configuration invalid
[FATAL][2020-10-26 19:25:11 +0100]
[FATAL][2020-10-26 19:25:11 +0100]	- Something went wrong connecting to aws. error: You must be logged in to the server (Unauthorized)
```

What could the omnipresent `error: You must be logged in to the server (Unauthorized)` refer to?

**Comment by camertron** [comment] 2020-10-26 21:09
I think you're seeing the repeated output because Kuby has been unable to refresh the kubeconfig, which it tries to do every time a `kubectl` command is run.

I have to admit, I'm a little out of my depth here since I haven't used EKS very much (only enough to get the kuby-eks gem working). AWS in general is so complicated you may have to do something special to get Kuby to work for your specific setup. Anyway, here's my understanding of what may be going on.

The kuby-eks gem uses [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) to authenticate users/roles. Specifically it allows you to use IAM to control who has access to your cluster and what they can access. By default, the account that created the cluster has `system:masters` access, which I think must be what I had when I was playing around with EKS a few months ago. I was able to use my own user account to do whatever I needed in the cluster. It sounds like that's not the case for you.

aws-iam-authenticator has this concept of mapUsers/mapRoles, which is supposed to be able to let you explicitly map IAM users/roles to kubernetes users/groups. You can apply special CRDs to your cluster that add these mappings, eg (from the aws-iam-authenticator docs):

```yaml
---
apiVersion: iamauthenticator.k8s.aws/v1alpha1
kind: IAMIdentityMapping
metadata:
  name: kubernetes-admin
spec:
  # Arn of the User or Role to be allowed to authenticate
  arn: arn:aws:iam::XXXXXXXXXXXX:user/KubernetesAdmin
  # Username that Kubernetes will see the user as, this is useful for setting
  # up allowed specific permissions for different users
  username: kubernetes-admin
  # Groups to be attached to your users/roles. For example `system:masters` to
  # create cluster admin, or `system:nodes`, `system:bootstrappers` for nodes to
  # access the API server.
  groups:
  - system:masters
```

For now, you could simply map your IAM user to `system:masters` to test things out.

This is making me think Kuby needs to do a little more explicit user management. Right now it uses the default user, which may or may not have access to the objects/APIs it needs to deploy.

**Comment by lazyatom** [comment] 2020-10-28 14:45
Is it possible that this is also being caused by stale cached `kubeconfig.yaml` data? (#40)

**Comment by camertron** [comment] 2020-10-28 17:29
@lazyatom maybe, but IAM/permissions in the AWS world are notoriously complicated, and I've had conversations in the past with co-workers knowledgeable about EKS who have mentioned the `system:masters` issue. The particular error message @momolog posted seems to indicate a successful connection to AWS (i.e. the cert is valid), but the user running the commands doesn't have the requisite permissions to make changes to the cluster.

That being said, the stale kubeconfig issue is definitely something I (or another enterprising dev) need to address right away.

**Comment by camertron** [comment] 2021-04-27 22:51
@momolog I'm going to close this for now. If you have any additional info, please comment here.

**Closed by camertron** 2021-04-27 22:51 UTC
